In [4]:
pip install numpy 

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ----- ---------------------------------- 1.6/12.6 MB 7.6 MB/s eta 0:00:02
   ---------- ----------------------------- 3.4/12.6 MB 8.1 MB/s eta 0:00:02
   --------------- ------------------------ 5.0/12.6 MB 8.0 MB/s eta 0:00:01
   --------------------- ------------------ 6.8/12.6 MB 7.9 MB/s eta 0:00:01
   ------------------------ --------------- 7.6/12.6 MB 7.0 MB/s eta 0:00:01
   ----------------------------- ---------- 9.2/12.6 MB 6.9 MB/s eta 0:00:01
   --------------------------------- ------ 10.5/12.6 MB 6.7 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.6 MB 6.8 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 6.6 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: C:\Users\debab\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [5]:
pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ----------------------- ---------------- 1.0/1.8 MB 6.3 MB/s eta 0:00:01
   ---------------------------------------- 1.8/1.8 MB 5.9 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np
from datetime import datetime

In [234]:
np_arr = np.array([1,2,3])
np_arr_2d = np.array([ [1,2,3] , 
                  [4,5,6] ])

np_arr_2d_new = np.array([ [1,2,3,5] , 
                  [4,5,6, 5] , 
                   [1, 3 , 4,2] ])
print(type(np_arr))
print(np_arr)

<class 'numpy.ndarray'>
[1 2 3]


In [ ]:
help(np)

In [ ]:

# size returns how many elements are there in the array
print("size")
print(np_arr.size )
print( np_arr_2d.size)
print( np_arr_2d_new.size)

print("shape")
print(np_arr.shape )
print( np_arr_2d.shape)
print( np_arr_2d_new.shape)


print("ndim")
print(np_arr.ndim )
print( np_arr_2d.ndim)
print( np_arr_2d_new.ndim)


size
3
6
12
shape
(3,)
(2, 3)
(3, 4)
ndim
1
2
2


In [29]:
np_mean = np.mean(np_arr_2d)
print(np_mean)

3.5


In [30]:
np_median = np.median(np_arr_2d)
print(np_mean)

3.5


In [236]:
print(np.sort(np_arr_2d_new))
print(np_arr_2d_new)

[[1 2 3 5]
 [4 5 5 6]
 [1 2 3 4]]
[[1 2 3 5]
 [4 5 6 5]
 [1 3 4 2]]


In [237]:
np_arr[0:]
print(np_arr_2d)
print(np_arr_2d[0][-1])
print(np_arr_2d_new[ 1:3 ,1:3 ])

[[1 2 3]
 [4 5 6]]
3
[[5 6]
 [3 4]]


In [63]:
print(np_arr_2d_new)
# print(np.sort(np_arr_2d_new))
# print(np_arr_2d_new)
np_arr_2d_sorted  =np.sort(np_arr_2d_new )
print(np_arr_2d_sorted)
print(np_arr_2d_sorted[0][-1::-1])
print(np_arr_2d_new)

[[1 2 3 5]
 [4 5 6 5]
 [1 3 4 2]]
[[1 2 3 5]
 [4 5 5 6]
 [1 2 3 4]]
[5 3 2 1]
[[1 2 3 5]
 [4 5 6 5]
 [1 3 4 2]]


In [67]:
zero_arr = np.ones( (5,3))
print(zero_arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [72]:
new_arr = np_arr_2d_new.reshape(  4,3)
print(np_arr_2d_new)

[[1 2 3 5]
 [4 5 6 5]
 [1 3 4 2]]


In [71]:
new_arr

array([[1, 2, 3],
       [5, 4, 5],
       [6, 5, 1],
       [3, 4, 2]])

### mini project 

In [73]:
import random as rn

In [81]:
rn.randint(30,40)

34

In [240]:
# temp = np.zeros(30)
# for i in  range(0,30):
#     temp[i] = rn.randint(30 , 40 )


# temp = np.random.uniform(30 , 40 , 30 )
temp = np.random.randint(30 , 40 , 30 )
avg_temp = int(np.average(temp))
print( f'mean : { int(np.mean(temp)) } | median : { int(np.median(temp)) } | standard_deviation : {int ( np.std(temp)) }')
above_average = list( filter( lambda x : x>avg_temp , temp)  )
print( f' No. of days temparature was above average is {len(above_average)}')

## shorter technic
# print( f' No. of days temparature was above average is {temp[temp>avg_temp].size}')

mean : 34 | median : 34 | standard_deviation : 2
 No. of days temparature was above average is 14


In [123]:
arr = np.random.rand(4,5)
print(arr)

[[0.16526267 0.97190472 0.14721146 0.29344309 0.38634349]
 [0.40755778 0.40147551 0.86997801 0.4411496  0.76787565]
 [0.8156086  0.58118863 0.70290615 0.49075591 0.89381831]
 [0.1597203  0.94562586 0.86113267 0.17772434 0.22288475]]


In [125]:
import numpy as np
np.random.seed(10)
np.random.randint(30, 40 , 10)

array([39, 34, 30, 31, 39, 30, 31, 38, 39, 30], dtype=int32)

## view vs copy

In [127]:
arr = np.array([1,2,3,4,5,6,7,8])

print (arr)
arr1 = arr[1:4]
arr1[1] = 10

print(arr)
print(arr1)

[1 2 3 4 5 6 7 8]
[ 1  2 10  4  5  6  7  8]
[ 2 10  4]


In [128]:
arr = np.array([1,2,3,4,5,6,7,8])

print (arr)
arr1 = arr[1:4].copy()
arr1[1] = 10

print(arr)
print(arr1)

[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]
[ 2 10  4]


In [134]:
new_arr = np.arange(1,15)
b= new_arr[new_arr > 10]
b[:] =0
print(new_arr)
new_arr/0

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


C:\Users\debab\AppData\Local\Temp\ipykernel_20476\1211754435.py:5: RuntimeWarning: divide by zero encountered in divide
  new_arr/0


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf])

## numpy vs. list 
- numpy array is taking less space than list 
- numpy array has better performance while working big datasets 

In [146]:
%timeit [i for i in range(1,1000000)]


44.6 ms ± 1.11 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
%timeit np.arange(1,1000000)

2.52 ms ± 32.4 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [152]:
arr = np.array([10,20,30,40,50])
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.sqrt(arr))
print(np.sin(arr))
print(np.cos(arr))
print(np.sum(arr))

10
50
0
4
[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
[-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]
[-0.83907153  0.40808206  0.15425145 -0.66693806  0.96496603]
150


In [151]:
np.linspace(2,10,5)

array([ 2.,  4.,  6.,  8., 10.])

In [242]:
arr = np.array( [ [10,20,30,40,50] , [60,70,80,10,100] ])
print(np.min(arr , axis=0 ))
print(np.max(arr , axis=1))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.sqrt(arr))
print(np.sin(arr))
print(np.cos(arr))
print(np.sum(arr))

[10 20 30 10 50]
[ 50 100]
0
9
[[ 3.16227766  4.47213595  5.47722558  6.32455532  7.07106781]
 [ 7.74596669  8.36660027  8.94427191  3.16227766 10.        ]]
[[-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]
 [-0.30481062  0.77389068 -0.99388865 -0.54402111 -0.50636564]]
[[-0.83907153  0.40808206  0.15425145 -0.66693806  0.96496603]
 [-0.95241298  0.6333192  -0.11038724 -0.83907153  0.86231887]]
470


In [243]:
arr = np.array([10 ,20 ,30 ,40 ,10 ,20 ])
new_arr = np.unique(arr)
print(np.unique(arr , return_counts=True , return_index=True))
print(arr)
print(new_arr)
np.random.shuffle(arr)
print(arr)

(array([10, 20, 30, 40]), array([0, 1, 2, 3]), array([2, 2, 1, 1]))
[10 20 30 40 10 20]
[10 20 30 40]
[40 30 20 20 10 10]


In [160]:
import numpy as np

In [244]:
arr = np.array([10,20,30,40,50])
arr1 = np.random.randint(10,20 , 10)

In [200]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [181]:
arr2 = np.random.randint(10,20 , 9).reshape(3,3)
arr2

array([[18, 19, 11],
       [12, 18, 19],
       [19, 15, 10]], dtype=int32)

In [197]:
arr1[arr1%2==0]=0
print(arr1)
# new_arr

[ 0  0  0 15  0  0  0  0 19 11]


In [195]:
np.random.rand(3,3)

array([[0.36536497, 0.21876935, 0.75249617],
       [0.10687958, 0.74460324, 0.46978529],
       [0.59825567, 0.14762019, 0.18403482]])

In [245]:
arr_2d = np.arange(1,17).reshape(4,4)
arr_2d_1 = np.arange(20,36).reshape(4,4)
arr_2d_1

array([[20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [247]:
np.hstack((arr_2d_1 , arr_2d , arr_2d ))

array([[20, 21, 22, 23,  1,  2,  3,  4,  1,  2,  3,  4],
       [24, 25, 26, 27,  5,  6,  7,  8,  5,  6,  7,  8],
       [28, 29, 30, 31,  9, 10, 11, 12,  9, 10, 11, 12],
       [32, 33, 34, 35, 13, 14, 15, 16, 13, 14, 15, 16]])

In [217]:
np.vstack((arr_2d , arr_2d_1))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [ ]:
arr_2d[ 1: , 1:3 ]

array([[ 6,  7],
       [10, 11],
       [14, 15]])

In [233]:
where_arr = np.where(arr==10)
print(where_arr)

(array([0]),)


In [228]:
np.where?

Call signature:  np.where(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <built-in function where>
Docstring:      
where(condition, [x, y], /)

Return elements chosen from `x` or `y` depending on `condition`.

.. note::
    When only `condition` is provided, this function is a shorthand for
    ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
    preferred, as it behaves correctly for subclasses. The rest of this
    documentation covers only the case where all three arguments are
    provided.

Parameters
----------
condition : array_like, bool
    Where True, yield `x`, otherwise yield `y`.
x, y : array_like
    Values from which to choose. `x`, `y` and `condition` need to be
    broadcastable to some shape.

Returns
-------
out : ndarray
    An array with elements from `x` where `condition` is True, and elements
    from `y` elsewhere.

See Also
--------
choose
nonzero : The function that is called when x and y are omitted

Notes
